name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      # 1. Buat project flutter sementara
      - run: flutter create temp_app

      # 2. Hapus file bawaan yang tidak perlu
      - run: rm temp_app/lib/main.dart
      - run: rm temp_app/pubspec.yaml

      # 3. Salin SEMUA file kodingan DAN pubspec.yaml milikmu ke project
      - run: cp -r lib/* temp_app/lib/
      - run: cp pubspec.yaml temp_app/

      # 4. Jalankan perintah di dalam folder temp_app
      - run: |
          cd temp_app
          flutter pub get
          flutter build apk --release

      # 5. Upload hasilnya
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: temp_app/build/app/outputs/flutter-apk/app-release.apk
